### PR TITLE
Include KitchenAid brand

### PR DESCRIPTION
**Pull request by MizterB**
Enable communication with KitchenAid brand appliances

### CODE REVIEW

**Review by abmantis — APPROVED** [review]
Thanks!

**Comment by mkmer** [comment]
This is an interesting development - I wonder how they do this with mixed brands on a users account...  My account is brand maytag (in the US) even though the appliances are whirlpool.  
I think we will have some challenges on the HA integration configuration as we move forward :(

**Comment by abmantis** [comment]
> This is an interesting development - I wonder how they do this with mixed brands on a users account... My account is brand maytag (in the US) even though the appliances are whirlpool. I think we will have some challenges on the HA integration configuration as we move forward :(

But you use the Whirlpool app, right? The Whirlpool app here (in EU) uses the whirlpool client_id. I assume that in the US it simply uses maytag for both Whirlpool + Maytag appliances.

**Comment by mkmer** [comment]
Correct - I'm in the US, using whirlpool android app AND have whirlpool appliances, yet must set the maytag brand for a successful login.  
So far, we didn't put a brand option on the HA config flow, and at least as far as I know, it will be confusing in the US.  Now that we have a kitchenaid brand too (assuming it's needed in EU?) we will need to put the brand selector in the config flow, and it will more than likely be confusing.  I suppose we could address it with the docs.

**Comment by abmantis** [comment]
In the Brand option, I think we could also have a default "Auto" brand, where the integration tries to auth one by one, and selects the one that succeeds.

**Pull request merged**
